"""empty message

Revision ID: 640a8a39f480
Revises: 
Create Date: 2019-12-31 14:07:57.745241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '640a8a39f480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('sample', sa.Column('date_updated', sa.Date(), nullable=True))
    op.alter_column('sample', 'access_level',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample', 'access_level',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.drop_column('sample', 'date_updated')
    op.drop_column('sample', 'date_created')
    # ### end Alembic commands ###
