"""empty message

Revision ID: 74c7fda601eb
Revises: 640a8a39f480
Create Date: 2020-01-03 14:02:43.983406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c7fda601eb'
down_revision = '640a8a39f480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('created_by', sa.String(length=300), nullable=True))
    op.add_column('sample', sa.Column('updated_by', sa.String(length=300), nullable=True))
    op.add_column('sample_version', sa.Column('created_by', sa.String(length=300), autoincrement=False, nullable=True))
    op.add_column('sample_version', sa.Column('updated_by', sa.String(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_version', 'updated_by')
    op.drop_column('sample_version', 'created_by')
    op.drop_column('sample', 'updated_by')
    op.drop_column('sample', 'created_by')
    # ### end Alembic commands ###
