"""empty message

Revision ID: 8478d53a3c34
Revises: 74c7fda601eb
Create Date: 2020-07-10 18:07:59.593915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8478d53a3c34'
down_revision = '74c7fda601eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmpdata', sa.Column('data_custodian', sa.String(length=300), nullable=True))
    op.add_column('dmpdata', sa.Column('source_dna_type', sa.String(length=300), nullable=True))
    op.add_column('dmpdata', sa.Column('tempo_output_delivery_date', sa.String(length=300), nullable=True))
    op.add_column('dmpdata', sa.Column('tempo_qc_status', sa.String(length=300), nullable=True))
    op.add_column('dmpdata_version', sa.Column('data_custodian', sa.String(length=300), autoincrement=False, nullable=True))
    op.add_column('dmpdata_version', sa.Column('source_dna_type', sa.String(length=300), autoincrement=False, nullable=True))
    op.add_column('dmpdata_version', sa.Column('tempo_output_delivery_date', sa.String(length=300), autoincrement=False, nullable=True))
    op.add_column('dmpdata_version', sa.Column('tempo_qc_status', sa.String(length=300), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('alt_id', sa.String(length=300), nullable=True))
    op.add_column('sample_version', sa.Column('alt_id', sa.String(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_version', 'alt_id')
    op.drop_column('sample', 'alt_id')
    op.drop_column('dmpdata_version', 'tempo_qc_status')
    op.drop_column('dmpdata_version', 'tempo_output_delivery_date')
    op.drop_column('dmpdata_version', 'source_dna_type')
    op.drop_column('dmpdata_version', 'data_custodian')
    op.drop_column('dmpdata', 'tempo_qc_status')
    op.drop_column('dmpdata', 'tempo_output_delivery_date')
    op.drop_column('dmpdata', 'source_dna_type')
    op.drop_column('dmpdata', 'data_custodian')
    # ### end Alembic commands ###
