const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_INVALID= 'USER_LOGIN_INVALID';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
const OPERATION_ERROR = 'OPERATION_ERROR';